name: Lighthouse Custom Config

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 2 * * *'
  repository_dispatch:
    types: lighthouse

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run Lighthouse on urls and validate with lighthouserc
        uses: treosh/lighthouse-ci-action@v2
        with:
          urls: |
            https://www.pomelofashion.com/th/en/
          runs: 1
          configPath: '.github/lighthouse/lighthouserc-custom-config.json'
          uploadArtifacts: true