name: Lighthouse

on:
  schedule:
    - cron: '0 2 * * *'
  repository_dispatch:
    types: lighthouse

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run Lighthouse on urls and validate with lighthouserc
        uses: treosh/lighthouse-ci-action@v2
        with:
          urls: |
            https://www.google.co.th
          runs: 1
          budgetPath: '.github/lighthouse/budget.json'
          uploadArtifacts: true